apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbs-postgres
  labels:
    db: pbs-postgres
spec:
  selector:
    matchLabels:
      db: pbs-postgres
  template:
    metadata:
      labels:
        db: pbs-postgres
    spec:
      containers:
        - name: pbs-postgres
          image: postgres:15.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pbs-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pbs-db-secret
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: pbs-postgres-init-config

---

apiVersion: v1
kind: Service
metadata:
  name: pbs-postgres
  labels:
    db: pbs-postgres
spec:
  type: ClusterIP
  selector:
    db: pbs-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

#kubectl apply -f k8s/manifest/postgresql.yaml

#kubectl delete -f k8s/manifest/postgresql.yaml
