apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-databases
data:
  init.sql: |
    CREATE DATABASE polardb_catalog;
    CREATE DATABASE polardb_order;

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    db: polar-rabbitmq
data:
  rabbitmq.conf: |
    default_user = user
    default_pass = password
    vm_memory_high_watermark.relative = 1.0

#kubectl apply -f k8s/manifest/config-map.yaml