---
# Определяет ClusterRole с правами администратора для Jenkins
# ClusterRole - это набор разрешений, действующих во всем кластере
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]  # Основная группа API (core API), пустая строка означает ядро Kubernetes
    resources: ["*"] # Доступ ко ВСЕМ ресурсам в кластере (поды, сервисы, ноды и т.д.)
    verbs: ["*"]     # Разрешены ВСЕ действия (get, list, create, delete, update, patch, watch и др.)
---
# Создает ServiceAccount для Jenkins
# ServiceAccount - это учетная запись для работы внутри кластера Kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin           # Имя ServiceAccount
  namespace: devops-tools       # Пространство имен, где будет создан ServiceAccount
---
# Связывает ClusterRole с ServiceAccount
# ClusterRoleBinding привязывает права к учетной записи во всем кластере
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole             # Тип привязываемой роли
  name: jenkins-admin           # Имя ClusterRole, определенной выше
subjects:
  - kind: ServiceAccount
    name: jenkins-admin         # Имя ServiceAccount, которому даются права
    namespace: devops-tools     # Пространство имен, где находится ServiceAccount

# kubectl apply -f k8s/jenkins/manifest1/jenkins-01-serviceAccount.yaml