version: "3.8"
services:
  pbs-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: pbs-rabbitmq
    ports:
        #Порт, на котором RabbitMQ прослушивает запросы AMQP.
      - 5672:5672
        #Порт, который предоставляет доступ к файлу конфигурации
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - pbs-network

# docker-compose -f deployment/docker/rabbitmq/docker-compose.yaml up -d